[versions]
minSdk = "24"
compileSdk = "34"
targetSdk = "34"
kotlinVersion = "1.9.20"
lifecycleVersion = "2.7.0"
coroutinesVersion = "1.7.3"
espressoVersion = "3.5.1"

[plugins]
android-application = { id = "com.android.application", version = "8.1.1" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }

[libraries]

# Core
appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }
material = { module = "com.google.android.material:material", version = "1.11.0" }

# Lifecycle
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }

# Activity ktx
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.8.2" }

# Coroutines
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion" }

#-----------------------------------------------TEST-----------------------------------------------#
junit = { module = "junit:junit", version = "4.13.2" }
ext-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoVersion" }
